authorization:
  service: keycloak
search:
  service: none

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:9080/realms/realm

  data:
    mongodb:
      database: disposableemail
      host: localhost
      port: 0

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.21

keycloak:
  server:
    url: http://localhost:9080
    realm: master
    username: admin
    password: admin
    client: admin-cli

mail-server:
  name: server
  mailbox: inbox
  base-url: http://localhost:8000
  defaultUserSizeQuota: 4000
  quotaPath: /quota/users/

logging:
  level.root: debug

resilience4j:
  ratelimiter:
    instances:
      ratelimiterAccountRegistration:
        limitForPeriod: 5
        limitRefreshPeriod: 1m
        timeoutDuration: 2s