export const menu = [
    {
      id: 1,
      title: "Main",
      listItems: [
        {
          id: 1,
          title: "Home",
          url: "/",
          icon: "home.svg",
        },
        {
          id: 2,
          title: "Profile",
          url: "/users/1",
          icon: "profile.svg",
        },
      ],
    },
    {
      id: 2,
      title: "Lists",
      listItems: [
        {
          id: 1,
          title: "Domains",
          url: "/domains",
          icon: "domain.svg",
        },
        {
          id: 2,
          title: "Accounts",
          url: "/accounts",
          icon: "account.svg",
        },
      ],
    },
    {
      id: 3,
      title: "General",
      listItems: [
        {
          id: 1,
          title: "Health",
          url: "/",
          icon: "health.svg",
        },
        {
          id: 2,
          title: "API docs",
          url: "/docs",
          icon: "docs.svg",
        },
        {
          id: 3,
          title: "Security",
          url: "/",
          icon: "security.svg",
        },
      ],
    },
    {
      id: 4,
      title: "Maintenance",
      listItems: [
        {
          id: 1,
          title: "Settings",
          url: "/",
          icon: "settings.svg",
        },
        {
          id: 2,
          title: "Backups",
          url: "/",
          icon: "backup.svg",
        },
      ],
    },
    {
      id: 5,
      title: "Analytics",
      listItems: [
        {
          id: 1,
          title: "Metrics",
          url: "/",
          icon: "metrics.svg",
        },
        {
          id: 2,
          title: "Logs",
          url: "/",
          icon: "log.svg",
        },
      ],
    },
  ];
  export const topDomains = [
    {
      id: 1,
      domain: "example.com",
      amount: "68521",
    },
    {
      id: 2,
      domain: "example.xyz",
      amount: "66544",
    },
    {
      id: 3,
      domain: "example.net",
      amount: "56541",
    },
    {
      id: 4,
      domain: "example.eu",
      amount: "3545",
    },
    {
      id: 5,
      domain: "example.us",
      amount: "2544",
    },
    {
      id: 6,
      domain: "example.org",
      amount: "1654",
    },
  ];
  
  export const chartBoxAccount = {
    color: "#8884d8",
    icon: "/account.svg",
    title: "Total Accounts",
    number: "11.238",
    dataKey: "users",
    percentage: 45,
    chartData: [
      { name: "Sun", users: 400 },
      { name: "Mon", users: 600 },
      { name: "Tue", users: 500 },
      { name: "Wed", users: 700 },
      { name: "Thu", users: 400 },
      { name: "Fri", users: 500 },
      { name: "Sat", users: 450 },
    ],
  };
  
  export const chartBoxDomain = {
    color: "skyblue",
    icon: "/domain.svg",
    title: "Total Domains",
    number: "238",
    dataKey: "domains",
    percentage: 21,
    chartData: [
      { name: "Sun", domains: 400 },
      { name: "Mon", domains: 600 },
      { name: "Tue", domains: 500 },
      { name: "Wed", domains: 700 },
      { name: "Thu", domains: 400 },
      { name: "Fri", domains: 500 },
      { name: "Sat", domains: 450 },
    ],
  };
  export const chartBoxMessages = {
    color: "teal",
    icon: "/revenueIcon.svg",
    title: "Total Messages",
    number: "56.432",
    dataKey: "revenue",
    percentage: -12,
    chartData: [
      { name: "Sun", messages: 400 },
      { name: "Mon", messages: 600 },
      { name: "Tue", messages: 500 },
      { name: "Wed", messages: 700 },
      { name: "Thu", messages: 400 },
      { name: "Fri", messages: 500 },
      { name: "Sat", messages: 450 },
    ],
  };
       
  export const accountRows = [
    {
      id: 1,
      address: "jon@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 2,
      address: "doe@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 3,
      address: "test@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 4,
      address: "test2@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 5,
      address: "test3@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 6,
      address: "test4@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 7,
      address: "test6@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 8,
      address: "test8@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 9,
      address: "test9@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 10,
      address: "test10@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 11,
      address: "test11@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 12,
      address: "test12@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 13,
      address: "test13@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 14,
      address: "test14@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    {
      id: 15,
      address: "test15@example.com",
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
  ];
  
  export const domains = [
    {
      id: 1,
      domain: "example.com",
      isActive: true,
      isPrivate: true,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 2,
      domain: "example.xyz",
      isActive: true,
      isPrivate: false,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 3,
      domain: "domain.com",
      isActive: false,
      isPrivate: false,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 4,
      domain: "custom.com",
      isActive: true,
      isPrivate: false,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 5,
      domain: "example.eu",
      isActive: true,
      isPrivate: true,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 6,
      domain: "example.net",
      isActive: true,
      isPrivate: false,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 7,
      domain: "example.org",
      isActive: true,
      isPrivate: false,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 8,
      domain: "example.us",
      isActive: false,
      isPrivate: false,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 9,
      domain: "example.dot",
      isActive: true,
      isPrivate: true,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
    {
      id: 10,
      domain: "host.com",
      isActive: true,
      isPrivate: true,
      createdAt: "01.02.2023",
      updatedAt: "01.02.2023",
    },
  ];
    
  export const singleAccount = {
    id: 1,
    title: "johndoe@example.com",
    info: {
      quota: 1354,
      used: 351,
      isDisabled: "false",
      isDeleted: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    chart: {
      dataKeys: [
        { name: "messages", color: "#82ca9d" },
      ],
      data: [
        {
          name: "Sun",
          messages: 3879,
        },
        {
          name: "Mon",
          messages: 3000,
        },
        {
          name: "Tue",
          messages: 2000,
        },
        {
          name: "Wed",
          messages: 2780,
        },
        {
          name: "Thu",
          messages: 1565,
        },
        {
          name: "Fri",
          messages: 2390,
        },
        {
          name: "Sat",
          messages: 2548,
        },
      ],
    },
  };
  export const singleDomain = {
    id: 1,
    title: "example.com",
      info: {
      isActive: "true",
      isPrivate: "false",
      createdAt: "01.11.2023",
      updatedAt: "01.11.2023",
    },
    chart: {
      dataKeys: [
        { name: "messages", color: "#82ca9d" },
        { name: "accounts", color: "#8884d8" },
      ],
      data: [
        {
          name: "Sun",
          messages: 4000,
          accounts: 2400,
        },
        {
          name: "Mon",
          messages: 3000,
          accounts: 1398,
        },
        {
          name: "Tue",
          messages: 2000,
          accounts: 3800,
        },
        {
          name: "Wed",
          messages: 2780,
          accounts: 3908,
        },
        {
          name: "Thu",
          messages: 1890,
          accounts: 4800,
        },
        {
          name: "Fri",
          messages: 2390,
          accounts: 3800,
        },
        {
          name: "Sat",
          messages: 3490,
          accounts: 4300,
        },
      ],
    },
  };