openapi: 3.0.3
info:
  title: disposable-email-project-admin
  description: 'Disposable Email Project Admin API'
  version: 0.0.1
servers:
  - url: http://localhost:8089/api/v1
    description: 'Development server'
  - url: https://api.production-server.com/api/v1
    description: 'Production server'
paths:
  /domains:
    post:
      security:
        - bearerAuth: []
      operationId: createDomainItem
      requestBody:
        description: The new Domain Resource
        content:
          application/json:
            schema:
              $ref: '../schemas/schemas.yaml#/components/schemas/DomainItem'
      responses:
        '202':
          $ref: './responses/domain-responses.yaml#/components/responses/202'
        '204':
          $ref: './responses/domain-responses.yaml#/components/responses/204'
        '400':
          $ref: './responses/domain-responses.yaml#/components/responses/400'
        '404':
          $ref: './responses/domain-responses.yaml#/components/responses/404'
        '409':
          $ref: './responses/domain-responses.yaml#/components/responses/409'
      summary: Creates a Domain resource.
      description: Creates a Domain resource.
    get:
      operationId: getDomainCollection
      responses:
        '200':
          $ref: './responses/domains-responses.yaml#/components/responses/200'
      summary: Retrieves the collection of Domain resources.
      description: Retrieves the collection of Domain resources.
      parameters:
        - $ref: './parameters/query/domainsAllCollectionSize.yaml'
      deprecated: false
    parameters: []
  /domains/{id}:
    get:
      operationId: getDomainItem
      responses:
        '200':
          $ref: './responses/domain-responses.yaml#/components/responses/200'
        '404':
          $ref: './responses/domain-responses.yaml#/components/responses/404'
      summary: Retrieves a Domain resource.
      description: Retrieves a Domain resource.
      parameters:
        - $ref: './parameters/path/domainId.yaml'
      deprecated: false
    parameters: []
    delete:
      security:
        - bearerAuth: []
      operationId: deleteDomainItem
      responses:
        '204':
          description: Domain deleted
        '404':
          $ref: './responses/domain-responses.yaml#/components/responses/404'
      summary: Removes the Domain resource.
      description: Removes the Domain resource.
      parameters:
        - $ref: './parameters/path/domainId.yaml'
      deprecated: false
  /accounts:
    post:
      operationId: createAccountItem
      requestBody:
        description: The new Account Resource
        content:
          application/json:
            schema:
              $ref: '../schemas/schemas.yaml#/components/schemas/Credentials'
      responses:
        '202':
          $ref: './responses/account-responses.yaml#/components/responses/202'
        '400':
          $ref: './responses/account-responses.yaml#/components/responses/400'
        '401':
          $ref: './responses/account-responses.yaml#/components/responses/401'
        '422':
          $ref: './responses/account-responses.yaml#/components/responses/422'
        '409':
          $ref: './responses/account-responses.yaml#/components/responses/409'
      summary: Creates an Account resource.
      description: Creates an Account resource.
    get:
      security:
        - bearerAuth: []
      operationId: getAccountCollection
      responses:
        '200':
          $ref: './responses/accounts-responses.yaml#/components/responses/200'
      summary: Retrieves the collection of Account resources.
      description: Retrieves the collection of Account resources.
      parameters:
        - $ref: './parameters/query/accountsCollectionSize.yaml'
        - $ref: './parameters/query/accountsCollectionOffset.yaml'
      deprecated: false
    parameters: []
  /accounts/{id}:
    get:
      security:
        - bearerAuth: []
      operationId: getAccountItem
      responses:
        '200':
          $ref: './responses/account-responses.yaml#/components/responses/200'
        '404':
          $ref: './responses/account-responses.yaml#/components/responses/404'
      summary: Retrieves a Account resource.
      description: Retrieves a Account resource.
      parameters:
        - $ref: './parameters/path/accountId.yaml'
      deprecated: false
    delete:
      security:
        - bearerAuth: []
      operationId: deleteAccountItem
      responses:
        '204':
          $ref: './responses/account-responses.yaml#/components/responses/204'
        '404':
          $ref: './responses/account-responses.yaml#/components/responses/404'
      summary: Removes the Account resource.
      description: Removes the Account resource.
      parameters:
        - $ref: './parameters/path/accountId.yaml'
      deprecated: false
  /token:
    post:
      operationId: postCredentialsItem
      responses:
        '200':
          $ref: './responses/token-responses.yaml#/components/responses/200'
        '401':
          $ref: './responses/token-responses.yaml#/components/responses/401'
      summary: Get JWT token to login.
      description: ''
      parameters: []
      requestBody:
        description: Generate new JWT Token
        content:
          application/json:
            schema:
              $ref: '../schemas/schemas.yaml#/components/schemas/Credentials'
        required: false
      deprecated: false
    parameters: []
